# Generated by Django 5.2.17 on 2026-09-04 09:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=60)),
                ('lga', models.CharField(blank=True, max_length=60)),
                ('typical_price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'markets_buyer',
                'ordering': ['-verified', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=60)),
                ('lga', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'markets_market',
                'ordering': ['state', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'state'), name='unique_market_per_state')],
            },
        ),
        migrations.CreateModel(
            name='FeedPrice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_on', models.DateField()),
                ('starter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('grower', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('finisher', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('layer', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_prices', to='markets.market')),
            ],
            options={
                'db_table': 'markets_feed_price',
                'ordering': ['-recorded_on', 'market__name'],
                'constraints': [models.UniqueConstraint(fields=('market', 'recorded_on'), name='one_feed_price_per_market_per_day')],
            },
        ),
    ]
