# Generated by Django 5.2.17 on 2026-09-11 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_organisation'),
        ('flocks', '0007_weight_standards_for_nigeria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('period_start', models.DateField(help_text='First day member farms are covered.')),
                ('period_end', models.DateField(help_text='Last day member farms are covered.')),
                ('farms_count', models.PositiveIntegerField()),
                ('price_per_farm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='farms.organisation')),
            ],
            options={
                'db_table': 'billing_coop_invoice',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('batch', 'One batch'), ('month', 'One month')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Waiting for payment'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('covers_from', models.DateField(blank=True, null=True)),
                ('covers_until', models.DateField(blank=True, null=True)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='flocks.batch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='farms.farm')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', 'status', 'covers_until'], name='billing_pay_farm_id_e622f4_idx')],
            },
        ),
    ]
