# Generated by Django 5.2.17 on 2026-09-04 09:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('broiler', 'Broilers'), ('layer', 'Layers'), ('cockerel', 'Cockerels'), ('noiler', 'Noilers'), ('mixed', 'Mixed')], max_length=20, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('cycle_days', models.PositiveSmallIntegerField(help_text='Days to the milestone the farmer is working towards.')),
                ('cycle_goal', models.CharField(help_text="What that milestone is, e.g. 'to market', 'to first egg'.", max_length=60)),
            ],
            options={
                'db_table': 'flocks_bird_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('bird_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breeds', to='flocks.birdtype')),
            ],
            options={
                'db_table': 'flocks_breed',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('started_on', models.DateField(help_text='The day the birds were stocked.')),
                ('stocked', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cost_per_bird', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('supplier', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='farms.farm')),
                ('pen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='farms.pen')),
                ('bird_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='flocks.birdtype')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='flocks.breed')),
            ],
            options={
                'db_table': 'flocks_batch',
                'ordering': ['-started_on', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logged_on', models.DateField()),
                ('feed_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('death_cause', models.CharField(blank=True, choices=[('sudden', 'Sudden death'), ('disease', 'Disease symptoms'), ('predator', 'Predator'), ('other', 'Other')], max_length=20)),
                ('health_activity', models.CharField(choices=[('none', 'Nothing today'), ('vaccine', 'Gave a vaccine'), ('medicine', 'Gave medicine'), ('vet', 'Vet visited')], default='none', max_length=20)),
                ('feed_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('meds_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('other_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='flocks.batch')),
            ],
            options={
                'db_table': 'flocks_daily_log',
                'ordering': ['-logged_on'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sold_on', models.DateField()),
                ('kind', models.CharField(choices=[('partial', 'Partial sale'), ('full', 'Full sale')], default='partial', max_length=20)),
                ('birds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('average_weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('buyer_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('restaurant', 'Restaurant'), ('supermarket', 'Supermarket'), ('wholesaler', 'Wholesaler'), ('other', 'Other')], max_length=20)),
                ('buyer_name', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='flocks.batch')),
            ],
            options={
                'db_table': 'flocks_sale',
                'ordering': ['-sold_on'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.PositiveSmallIntegerField(help_text='Day of the cycle the dose is due.')),
                ('name', models.CharField(max_length=120)),
                ('route', models.CharField(help_text="How it is given, e.g. 'Drinking water'.", max_length=60)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('bird_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedule', to='flocks.birdtype')),
            ],
            options={
                'db_table': 'flocks_vaccination_schedule',
                'ordering': ['bird_type', 'day'],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['farm', 'status'], name='flocks_batc_farm_id_584a14_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['batch', '-logged_on'], name='flocks_dail_batch_i_76de17_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('batch', 'logged_on'), name='one_log_per_batch_per_day'),
        ),
        migrations.AddConstraint(
            model_name='vaccinationschedule',
            constraint=models.UniqueConstraint(fields=('bird_type', 'day', 'name'), name='unique_dose_per_type_and_day'),
        ),
    ]
