# Generated by Django 5.2.17 on 2026-09-06 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPhase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Starter, Grower, Finisher.', max_length=60)),
                ('day_from', models.PositiveSmallIntegerField()),
                ('day_to', models.PositiveSmallIntegerField()),
                ('grams_per_bird_start', models.PositiveSmallIntegerField(help_text='Daily intake per bird on the first day of this phase.')),
                ('grams_per_bird_end', models.PositiveSmallIntegerField(help_text='Daily intake per bird on the last day of this phase.')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('bird_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_phases', to='flocks.birdtype')),
            ],
            options={
                'db_table': 'flocks_feed_phase',
                'ordering': ['bird_type', 'day_from'],
                'constraints': [models.UniqueConstraint(fields=('bird_type', 'day_from'), name='one_phase_per_start_day')],
            },
        ),
    ]
