# Generated by Django 5.2.17 on 2026-09-07 14:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0004_seed_feed_phases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weighing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weighed_on', models.DateField()),
                ('birds_weighed', models.PositiveSmallIntegerField(help_text='How many birds went on the scale.', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_weight_kg', models.DecimalField(decimal_places=2, help_text='What those birds weighed together.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('note', models.CharField(blank=True, max_length=300)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighings', to='flocks.batch')),
            ],
            options={
                'db_table': 'flocks_weighing',
                'ordering': ['-weighed_on'],
                'indexes': [models.Index(fields=['batch', '-weighed_on'], name='flocks_weig_batch_i_d95a88_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'weighed_on'), name='one_weighing_per_batch_per_day')],
            },
        ),
        migrations.CreateModel(
            name='WeightStandard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.PositiveSmallIntegerField(help_text='Day of the cycle.')),
                ('grams', models.PositiveIntegerField(help_text='Expected live weight on that day, in grams.')),
                ('bird_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_standards', to='flocks.birdtype')),
            ],
            options={
                'db_table': 'flocks_weight_standard',
                'ordering': ['bird_type', 'day'],
                'constraints': [models.UniqueConstraint(fields=('bird_type', 'day'), name='one_weight_standard_per_day')],
            },
        ),
    ]
