# Generated by Django 5.2.17 on 2026-09-04 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('lga', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'farms_farm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Farm manager'), ('attendant', 'Pen attendant'), ('viewer', 'Viewer')], default='owner', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='farms.farm')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farms_membership',
                'ordering': ['role', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='members',
            field=models.ManyToManyField(related_name='farms', through='farms.Membership', through_fields=('farm', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pens', to='farms.farm')),
            ],
            options={
                'db_table': 'farms_pen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='pens',
            field=models.ManyToManyField(blank=True, related_name='attendants', to='farms.pen'),
        ),
        migrations.AddConstraint(
            model_name='pen',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='unique_pen_name_per_farm'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'farm'), name='unique_membership_per_farm'),
        ),
    ]
