# Generated by Django 5.2.17 on 2026-09-07 19:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('cooperative', 'Cooperative'), ('scheme', 'Out-grower scheme'), ('mill', 'Feed mill'), ('other', 'Other')], default='cooperative', max_length=20)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('lga', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'farms_organisation',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='farms.organisation'),
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('officer', 'Field officer'), ('viewer', 'Viewer')], default='officer', max_length=20)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='farms.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farms_organisation_membership',
                'ordering': ['organisation', 'user'],
                'constraints': [models.UniqueConstraint(fields=('user', 'organisation'), name='one_membership_per_organisation')],
            },
        ),
    ]
